In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
df = pd.read_csv('betsdata_a2.csv')

In [6]:
df.shape

(983042, 26)

In [7]:
df

,BET_DATE,PLAYER_ID,PRODUCT,CHANNEL,PLATFORM,GAME_CATEGORY,GAME_NAME,BET_COUNT,BET_STATUS,PRODUCT_EXPERIENCE,...,PRODUCT_VARIANT,EVENT,EVENT_GROUP,MARKET_TYPE,MARKET,SUB_MARKET,SELECTION,PRICE,CURRENCY_ID,BONUS_COST
0,11/04/22,13567011,SPORTSBOOK,MOBILE,NaN,LIVE,Football,1,L,LIVE,...,Single,Inter Miami II v Orlando City II,USA - Reserves,1st Half - Total Goals,1st Half - Total Goals,1st Half - Total Goals,Over,11-May,TRY,0.0
1,11/04/22,11472902,SPORTSBOOK,MOBILE,NaN,LIVE,Football,1,S,LIVE,...,Single,Sao Paulo FC SP v CA Paranaense PR,Brazil - Serie A,1st Half Result,1st Half - Result,1st Half - Result,Sao Paulo FC SP,07-May,TRY,0.0
2,11/04/22,14396942,SPORTSBOOK,MOBILE,NaN,LIVE,Football,1,L,LIVE,...,Single,Fenerbahce Istanbul (Cliff) v Galatasaray (Moic),Esoccer - (12 Mins),1st Half - Total Goals,1st Half - Total Goals,1st Half - Total Goals,Over,06-Apr,TRY,0.0
3,11/04/22,148063171,SPORTSBOOK,WEB,NaN,LIVE,Football,1,W,LIVE,...,Single,CA River Plate v Argentinos Juniors,Argentina - Copa de la Liga,1st Half - Total Goals,1st Half - Total Goals,1st Half - Total Goals,Over,21/20,TRY,0.0
4,11/04/22,12581903,SPORTSBOOK,MOBILE,NaN,LIVE,Football,1,W,LIVE,...,Single,Achuapa (Reserves) v Comunicaciones (Reserves),Guatemala - Reserves,Full Time Total Goals,Total Goals,Total Goals,Over,01-Jan,TRY,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983037,10/04/22,11430549,SPORTSBOOK,WEB,NaN,PRE MATCH,Football,1,L,PRE MATCH,...,Single,Real Tomayapo v Blooming Guayaramerin,Bolivia - Primera Division,Full Time Total Goals,Total Goals,Total Goals,Over,10-Jan,TRY,0.0
983038,10/04/22,11430549,SPORTSBOOK,WEB,NaN,PRE MATCH,Football,1,L,PRE MATCH,...,Single,Real Tomayapo v Blooming Guayaramerin,Bolivia - Primera Division,Full Time Total Goals,Total Goals,Total Goals,Over,19-Apr,TRY,0.0
983039,10/04/22,11016063,SPORTSBOOK,MOBILE,NaN,LIVE,Football,19,L,LIVE,...,Accumulator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRY,0.0
983040,10/04/22,13659322,SPORTSBOOK,MOBILE,NaN,LIVE,Football,1,O,LIVE,...,Single,Union Espanola v Colo-Colo,Chile - Primera Division,Full Time Total Goals,Total Goals,Total Goals,Over,06-Apr,TRY,0.0
983041,10/04/22,14342149,SPORTSBOOK,WEB,NaN,PRE MATCH,Football,1,O,PRE MATCH,...,Single,Union Espanola v Colo-Colo,Chile - Primera Division,Full Time Total Goals,Total Goals,Total Goals,Over,11-May,TRY,0.0

In [8]:
df.isnull().sum()

BET_DATE                   0
PLAYER_ID                  0
PRODUCT                    0
CHANNEL                    0
PLATFORM              983042
GAME_CATEGORY              0
GAME_NAME                  0
BET_COUNT                  0
BET_STATUS                 0
PRODUCT_EXPERIENCE         0
CASH_BET_AMOUNT            0
CASH_WIN_AMOUNT            0
CASH_MARGIN                0
BONUS_BET_AMOUNT           0
BONUS_WIN_AMOUNT           0
BONUS_MARGIN               0
PRODUCT_VARIANT            0
EVENT                 400609
EVENT_GROUP           400609
MARKET_TYPE           400609
MARKET                400609
SUB_MARKET            400609
SELECTION             400609
PRICE                 400609
CURRENCY_ID                0
BONUS_COST                 0
dtype: int64

In [15]:
df['EVENT'] = df.fillna(df['EVENT'].mode())

In [16]:
df['EVENT_GROUP'] = df.fillna(df['EVENT_GROUP'].mode())

In [17]:
df['MARKET_TYPE'] = df.fillna(df['MARKET_TYPE'].mode())

In [18]:
df['MARKET'] = df.fillna(df['MARKET'].mode())
df['SUB_MARKET'] = df.fillna(df['SUB_MARKET'].mode())
df['PRICE'] = df.fillna(df['PRICE'].mode())
df['SELECTION'] = df.fillna(df['SELECTION'].mode())

In [19]:
df.isnull().sum()

BET_DATE              0
PLAYER_ID             0
PRODUCT               0
CHANNEL               0
GAME_CATEGORY         0
GAME_NAME             0
BET_COUNT             0
BET_STATUS            0
PRODUCT_EXPERIENCE    0
CASH_BET_AMOUNT       0
CASH_WIN_AMOUNT       0
CASH_MARGIN           0
BONUS_BET_AMOUNT      0
BONUS_WIN_AMOUNT      0
BONUS_MARGIN          0
PRODUCT_VARIANT       0
EVENT                 0
EVENT_GROUP           0
MARKET_TYPE           0
MARKET                0
SUB_MARKET            0
SELECTION             0
PRICE                 0
CURRENCY_ID           0
BONUS_COST            0
dtype: int64

In [20]:
df

,BET_DATE,PLAYER_ID,PRODUCT,CHANNEL,GAME_CATEGORY,GAME_NAME,BET_COUNT,BET_STATUS,PRODUCT_EXPERIENCE,CASH_BET_AMOUNT,...,PRODUCT_VARIANT,EVENT,EVENT_GROUP,MARKET_TYPE,MARKET,SUB_MARKET,SELECTION,PRICE,CURRENCY_ID,BONUS_COST
0,11/04/22,13567011,SPORTSBOOK,MOBILE,LIVE,Football,1,L,LIVE,0.93134,...,Single,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,TRY,0.0
1,11/04/22,11472902,SPORTSBOOK,MOBILE,LIVE,Football,1,S,LIVE,62.08963,...,Single,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,TRY,0.0
2,11/04/22,14396942,SPORTSBOOK,MOBILE,LIVE,Football,1,L,LIVE,1.55224,...,Single,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,TRY,0.0
3,11/04/22,148063171,SPORTSBOOK,WEB,LIVE,Football,1,W,LIVE,0.12418,...,Single,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,TRY,0.0
4,11/04/22,12581903,SPORTSBOOK,MOBILE,LIVE,Football,1,W,LIVE,31.04481,...,Single,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,11/04/22,TRY,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983037,10/04/22,11430549,SPORTSBOOK,WEB,PRE MATCH,Football,1,L,PRE MATCH,0.31045,...,Single,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,TRY,0.0
983038,10/04/22,11430549,SPORTSBOOK,WEB,PRE MATCH,Football,1,L,PRE MATCH,0.31045,...,Single,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,TRY,0.0
983039,10/04/22,11016063,SPORTSBOOK,MOBILE,LIVE,Football,19,L,LIVE,3.10448,...,Accumulator,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,TRY,0.0
983040,10/04/22,13659322,SPORTSBOOK,MOBILE,LIVE,Football,1,O,LIVE,31.04481,...,Single,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,TRY,0.0
983041,10/04/22,14342149,SPORTSBOOK,WEB,PRE MATCH,Football,1,O,PRE MATCH,1.24179,...,Single,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,10/04/22,TRY,0.0